language: go
os:
  - linux
  - osx
go:
  - go1.8
go_import_path: github.com/kataras/iris
install:
  - go get ./...
# install test dependencies
  - go get golang.org/x/tools/cmd/cover
  - go get -v github.com/axw/gocov
  - go install github.com/axw/gocov/gocov
script:
  - gocov test | gocov report